vpc_name               = "tf_test_vpc"
vpc_cidr               = "192.168.0.0/16"
subnet_name            = "tf_test_subnet"
security_group_name    = "tf_test_security_group"
instance_name          = "tf_test_instance"
administrator_password = "YourPasswordInput!"
