// Generated by PMS #1012
package swrenterprise

import (
	"context"
	"net/url"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
)

func DataSourceSwrEnterpriseInstanceArtifactAddition() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceSwrEnterpriseInstanceArtifactAdditionRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the enterprise instance ID.`,
			},
			"namespace_name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the namespace name.`,
			},
			"repository_name": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the repository name.`,
			},
			"reference": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the artifact digest.`,
			},
			"addition": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the addition info type.`,
			},
			"build_histories": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `Indicate the build histories.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"media_type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicate the media type.`,
						},
						"size": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: `Indicate the size.`,
						},
						"digest": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicate the digest.`,
						},
						"created": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicate the create time.`,
						},
						"created_by": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicate the create command.`,
						},
						"empty_layer": {
							Type:        schema.TypeBool,
							Computed:    true,
							Description: `Indicate whether it is the empty layer.`,
						},
					},
				},
			},
			"total": {
				Type:        schema.TypeInt,
				Computed:    true,
				Description: `Indicate the tital build histories.`,
			},
		},
	}
}

type InstanceArtifactAdditionDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newInstanceArtifactAdditionDSWrapper(d *schema.ResourceData, meta interface{}) *InstanceArtifactAdditionDSWrapper {
	return &InstanceArtifactAdditionDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceSwrEnterpriseInstanceArtifactAdditionRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newInstanceArtifactAdditionDSWrapper(d, meta)
	shoInsArtAddRst, err := wrapper.ShowInstanceArtifactAddition()
	if err != nil {
		return diag.FromErr(err)
	}

	err = wrapper.showInstanceArtifactAdditionToSchema(shoInsArtAddRst)
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)
	return nil
}

// nolint:revive
// @API SWR GET /v2/{project_id}/instances/{instance_id}/namespaces/{namespace_name}/repositories/{repository_name}/artifacts/{reference}/additions/{addition}
func (w *InstanceArtifactAdditionDSWrapper) ShowInstanceArtifactAddition() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "swr")
	if err != nil {
		return nil, err
	}

	// nolint:revive
	uri := "/v2/{project_id}/instances/{instance_id}/namespaces/{namespace_name}/repositories/{repository_name}/artifacts/{reference}/additions/{addition}"
	uri = strings.ReplaceAll(uri, "{instance_id}", w.Get("instance_id").(string))
	uri = strings.ReplaceAll(uri, "{namespace_name}", w.Get("namespace_name").(string))
	uri = strings.ReplaceAll(uri, "{repository_name}", url.PathEscape(strings.ReplaceAll(w.Get("repository_name").(string), "/", "%2F")))
	uri = strings.ReplaceAll(uri, "{reference}", w.Get("reference").(string))
	uri = strings.ReplaceAll(uri, "{addition}", w.Get("addition").(string))
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Request().
		Result()
}

func (w *InstanceArtifactAdditionDSWrapper) showInstanceArtifactAdditionToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("build_histories", schemas.SliceToList(body.Get("build_histories"),
			func(buildHistories gjson.Result) any {
				return map[string]any{
					"media_type":  buildHistories.Get("mediaType").Value(),
					"size":        buildHistories.Get("size").Value(),
					"digest":      buildHistories.Get("digest").Value(),
					"created":     buildHistories.Get("created").Value(),
					"created_by":  buildHistories.Get("created_by").Value(),
					"empty_layer": buildHistories.Get("empty_layer").Value(),
				}
			},
		)),
		d.Set("total", body.Get("total").Value()),
	)
	return mErr.ErrorOrNil()
}
