// Generated by PMS #510
package identitycenter

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
)

func DataSourceSystemIdentityPolicyAttachments() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceIdentitycenterSystemIdentityPolicyAttachmentsRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of an IAM Identity Center instance.`,
			},
			"permission_set_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of a permission set.`,
			},
			"policies": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The list of IAM system-defined identity policies.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The ID of the IAM system-defined identity policy.`,
						},
						"name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The name of the IAM system-defined identity policy.`,
						},
					},
				},
			},
		},
	}
}

type SystemIdentityPolicyAttachmentsDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newSystemIdentityPolicyAttachmentsDSWrapper(d *schema.ResourceData, meta interface{}) *SystemIdentityPolicyAttachmentsDSWrapper {
	return &SystemIdentityPolicyAttachmentsDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceIdentitycenterSystemIdentityPolicyAttachmentsRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newSystemIdentityPolicyAttachmentsDSWrapper(d, meta)
	lisManPolInPerSetRst, err := wrapper.ListManagedPoliciesInPermissionSet()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listManagedPoliciesInPermissionSetToSchema(lisManPolInPerSetRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API IDENTITYCENTER GET /v1/instances/{instance_id}/permission-sets/{permission_set_id}/managed-policies
func (w *SystemIdentityPolicyAttachmentsDSWrapper) ListManagedPoliciesInPermissionSet() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "identitycenter")
	if err != nil {
		return nil, err
	}

	uri := "/v1/instances/{instance_id}/permission-sets/{permission_set_id}/managed-policies"
	uri = strings.ReplaceAll(uri, "{instance_id}", w.Get("instance_id").(string))
	uri = strings.ReplaceAll(uri, "{permission_set_id}", w.Get("permission_set_id").(string))
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		MarkerPager("attached_managed_policies", " page_info.next_marker", "marker").
		Request().
		Result()
}

func (w *SystemIdentityPolicyAttachmentsDSWrapper) listManagedPoliciesInPermissionSetToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("policies", schemas.SliceToList(body.Get("attached_managed_policies"),
			func(policies gjson.Result) any {
				return map[string]any{
					"id":   policies.Get("policy_id").Value(),
					"name": policies.Get("policy_name").Value(),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
