// Generated by PMS #158
package waf

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/filters"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceWafRulesInformationLeakagePrevention() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceWafRulesInformationLeakagePreventionRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource.`,
			},
			"policy_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of the policy to which the information leakage prevention rules belong.`,
			},
			"rule_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the ID of the information leakage prevention rule.`,
			},
			"status": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the status of the information leakage prevention rule.`,
			},
			"type": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the type of the information leakage prevention rule.`,
			},
			"enterprise_project_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the enterprise project ID to which the protection policy belongs.`,
			},
			"rules": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The list of information leakage prevention rules.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The ID of the information leakage prevention rule.`,
						},
						"policy_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The ID of the policy to which the information leakage prevention rule belongs.`,
						},
						"status": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: `The status of the information leakage prevention rule.`,
						},
						"description": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The description of the information leakage prevention rule.`,
						},
						"path": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The path to which the information leakage prevention rule applies.`,
						},
						"type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The type of the information leakage prevention rule.`,
						},
						"contents": {
							Type:        schema.TypeList,
							Computed:    true,
							Elem:        &schema.Schema{Type: schema.TypeString},
							Description: `The contents of the information leakage prevention rule.`,
						},
						"protection_action": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The protection action of the information leakage prevention rule.`,
						},
						"created_at": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The creation time of the information leakage prevention rule.`,
						},
					},
				},
			},
		},
	}
}

type RulesInformationLeakagePreventionDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newRulesInformationLeakagePreventionDSWrapper(d *schema.ResourceData, meta interface{}) *RulesInformationLeakagePreventionDSWrapper {
	return &RulesInformationLeakagePreventionDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceWafRulesInformationLeakagePreventionRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newRulesInformationLeakagePreventionDSWrapper(d, meta)
	lisAntRulRst, err := wrapper.ListAntileakageRules()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listAntileakageRulesToSchema(lisAntRulRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API WAF GET /v1/{project_id}/waf/policy/{policy_id}/antileakage
func (w *RulesInformationLeakagePreventionDSWrapper) ListAntileakageRules() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "waf")
	if err != nil {
		return nil, err
	}

	uri := "/v1/{project_id}/waf/policy/{policy_id}/antileakage"
	uri = strings.ReplaceAll(uri, "{policy_id}", w.Get("policy_id").(string))
	params := map[string]any{
		"enterprise_project_id": w.Get("enterprise_project_id"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Query(params).
		OffsetPager("items", "offset", "limit", 100).
		Filter(
			filters.New().From("items").
				Where("id", "=", w.Get("rule_id")).
				Where("category", "=", w.Get("type")).
				Where("status", "=", w.GetToInt("status")),
		).
		OkCode(200).
		Request().
		Result()
}

func (w *RulesInformationLeakagePreventionDSWrapper) listAntileakageRulesToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("rules", schemas.SliceToList(body.Get("items"),
			func(rule gjson.Result) any {
				return map[string]any{
					"id":                rule.Get("id").Value(),
					"policy_id":         rule.Get("policyid").Value(),
					"status":            rule.Get("status").Value(),
					"description":       rule.Get("description").Value(),
					"path":              rule.Get("url").Value(),
					"type":              rule.Get("category").Value(),
					"contents":          schemas.SliceToStrList(rule.Get("contents")),
					"protection_action": rule.Get("action.category").Value(),
					"created_at":        w.setItemsTimestamp(rule),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}

func (*RulesInformationLeakagePreventionDSWrapper) setItemsTimestamp(data gjson.Result) string {
	rawDate := data.Get("timestamp").Int()
	return utils.FormatTimeStampRFC3339(rawDate/1000, false)
}
