// Generated by PMS #1005
package waf

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceWafProtectables() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceWafProtectablesRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"resource_type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the type of protection resource to query.`,
			},
			"vpc_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the VPC ID where the load balancer is located.`,
			},
			"items": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The detailed information on protectable resources.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"loadbalancer_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The load balancer name.`,
						},
						"loadbalancer_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The load balancer ID.`,
						},
						"domain_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The account ID to which the load balancer belongs.`,
						},
						"project_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The project ID.`,
						},
						"listeners": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: `The current list of listeners associated with ELB.`,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"name": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The name of the listener.`,
									},
									"id": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The ID of the listener.`,
									},
									"protocol": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The listening protocol of the listener.`,
									},
									"protocol_port": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The listening port of the listener.`,
									},
								},
							},
						},
						"eips": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: `The EIP bound to the load balancer.`,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"eip_id": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The elastic IP ID.`,
									},
									"eip_address": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The elastic IP address.`,
									},
									"ip_version": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The IP version.`,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

type ProtectablesDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newProtectablesDSWrapper(d *schema.ResourceData, meta interface{}) *ProtectablesDSWrapper {
	return &ProtectablesDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceWafProtectablesRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newProtectablesDSWrapper(d, meta)
	lisProResRst, err := wrapper.ListProtectableResources()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listProtectableResourcesToSchema(lisProResRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API WAF GET /v1/{project_id}/premium-waf/host/protectable-resources/{resource_type}
func (w *ProtectablesDSWrapper) ListProtectableResources() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "waf")
	if err != nil {
		return nil, err
	}

	uri := "/v1/{project_id}/premium-waf/host/protectable-resources/{resource_type}"
	uri = strings.ReplaceAll(uri, "{resource_type}", w.Get("resource_type").(string))
	params := map[string]any{
		"vpc_id": w.Get("vpc_id"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Query(params).
		Request().
		Result()
}

func (w *ProtectablesDSWrapper) listProtectableResourcesToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("items", schemas.SliceToList(body.Get("items"),
			func(items gjson.Result) any {
				return map[string]any{
					"loadbalancer_name": items.Get("loadbalancer_name").Value(),
					"loadbalancer_id":   items.Get("loadbalancer_id").Value(),
					"domain_id":         items.Get("domain_id").Value(),
					"project_id":        items.Get("project_id").Value(),
					"listeners": schemas.SliceToList(items.Get("listeners"),
						func(listeners gjson.Result) any {
							return map[string]any{
								"name":          listeners.Get("name").Value(),
								"id":            listeners.Get("id").Value(),
								"protocol":      listeners.Get("protocol").Value(),
								"protocol_port": listeners.Get("protocol_port").Value(),
							}
						},
					),
					"eips": schemas.SliceToList(items.Get("eips"),
						func(eips gjson.Result) any {
							return map[string]any{
								"eip_id":      eips.Get("eip_id").Value(),
								"eip_address": eips.Get("eip_address").Value(),
								"ip_version":  eips.Get("ip_version").Value(),
							}
						},
					),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
