// Generated by PMS #563
package vpc

import (
	"context"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceVpcQuotas() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceVpcQuotasRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"type": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the type of resource to filter quotas.`,
			},
			"quotas": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The quota objects.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"resources": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: `The resource objects.`,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"min": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The minimum quota value allowed.`,
									},
									"type": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The type of resource to filter quotas.`,
									},
									"used": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The number of created resources.`,
									},
									"quota": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The maximum quota values for the resources.`,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

type QuotasDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newQuotasDSWrapper(d *schema.ResourceData, meta interface{}) *QuotasDSWrapper {
	return &QuotasDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceVpcQuotasRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newQuotasDSWrapper(d, meta)
	showQuotaRst, err := wrapper.ShowQuota()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.showQuotaToSchema(showQuotaRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API VPC GET /v1/{project_id}/quotas
func (w *QuotasDSWrapper) ShowQuota() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "vpc")
	if err != nil {
		return nil, err
	}

	uri := "/v1/{project_id}/quotas"
	params := map[string]any{
		"type": w.Get("type"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Query(params).
		Request().
		Result()
}

func (w *QuotasDSWrapper) showQuotaToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("quotas", schemas.ObjectToList(body.Get("quotas"),
			func(quotas gjson.Result) any {
				return map[string]any{
					"resources": schemas.SliceToList(quotas.Get("resources"),
						func(resources gjson.Result) any {
							return map[string]any{
								"min":   resources.Get("min").Value(),
								"type":  resources.Get("type").Value(),
								"used":  resources.Get("used").Value(),
								"quota": resources.Get("quota").Value(),
							}
						},
					),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
