vpc_name                   = "tf_test_vpc"
subnet_name                = "tf_test_subnet"
security_group_name        = "tf_test_security_group"
dedicated_instance_name    = "tf_test_waf_instance"
dedicated_mode_domain_name = "www.example.com"
