// Generated by PMS #87
package taurusdb

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceGaussdbMysqlRestoreTimeRanges() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceGaussdbMysqlRestoreTimeRangesRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of the GaussDB MySQL instance.`,
			},
			"date": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the date to be queried.`,
			},
			"restore_times": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `Indicates the list of restoration time ranges.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"start_time": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: `Indicates the start time of the restoration time range in the UNIX timestamp format.`,
						},
						"end_time": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: `Indicates the end time of the restoration time range in the UNIX timestamp format.`,
						},
					},
				},
			},
		},
	}
}

type MysqlRestoreTimeRangesDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newMysqlRestoreTimeRangesDSWrapper(d *schema.ResourceData, meta interface{}) *MysqlRestoreTimeRangesDSWrapper {
	return &MysqlRestoreTimeRangesDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceGaussdbMysqlRestoreTimeRangesRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newMysqlRestoreTimeRangesDSWrapper(d, meta)
	shoBacResTimRst, err := wrapper.ShowBackupRestoreTime()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.showBackupRestoreTimeToSchema(shoBacResTimRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API GaussDBforMySQL GET /v3/{project_id}/instances/{instance_id}/restore-time
func (w *MysqlRestoreTimeRangesDSWrapper) ShowBackupRestoreTime() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "gaussdb")
	if err != nil {
		return nil, err
	}

	uri := "/v3/{project_id}/instances/{instance_id}/restore-time"
	uri = strings.ReplaceAll(uri, "{instance_id}", w.Get("instance_id").(string))
	params := map[string]any{
		"date": w.Get("date"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Query(params).
		Request().
		Result()
}

func (w *MysqlRestoreTimeRangesDSWrapper) showBackupRestoreTimeToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("restore_times", schemas.SliceToList(body.Get("restore_times"),
			func(restoreTimes gjson.Result) any {
				return map[string]any{
					"start_time": restoreTimes.Get("start_time").Value(),
					"end_time":   restoreTimes.Get("end_time").Value(),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
