// Generated by PMS #1053
package ccm

import (
	"context"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceCcmDeployeds() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceCcmDeployedsRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"service_names": {
				Type:        schema.TypeList,
				Required:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: `Specifies the service name list.`,
			},
			"certificate_ids": {
				Type:        schema.TypeList,
				Required:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: `Specifies the certificate ID list.`,
			},
			"results": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The request result list.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"certificate_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The certificate ID.`,
						},
						"total_num": {
							Type:        schema.TypeInt,
							Computed:    true,
							Description: `The number of resources deployed for the certificate in the current service.`,
						},
						"deployed_resources": {
							Type:        schema.TypeList,
							Computed:    true,
							Description: `The list of resources deployed under the current certificate.`,
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"region_resources": {
										Type:        schema.TypeList,
										Computed:    true,
										Description: `The region resource list.`,
										Elem:        resDepResRegResElem(),
									},
									"service": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The name of the resource service where the certificate has been deployed.`,
									},
									"resource_num": {
										Type:        schema.TypeInt,
										Computed:    true,
										Description: `The number of resources deployed for the certificate in the current service.`,
									},
									"resource_location": {
										Type:        schema.TypeString,
										Computed:    true,
										Description: `The global service or region-level service.`,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

// resDepResRegResElem
// The Elem of "results.deployed_resources.region_resources"
func resDepResRegResElem() *schema.Resource {
	return &schema.Resource{
		Schema: map[string]*schema.Schema{
			"region_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `The region ID.`,
			},
			"is_error": {
				Type:     schema.TypeBool,
				Computed: true,
				Description: `Whether an exception occurs in the response when the resource information of the
				 current region is requested.`,
			},
			"resources": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The resource set.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"resource_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The resource ID.`,
						},
						"resource_name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The resource name.`,
						},
					},
				},
			},
		},
	}
}

type DeployedsDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newDeployedsDSWrapper(d *schema.ResourceData, meta interface{}) *DeployedsDSWrapper {
	return &DeployedsDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceCcmDeployedsRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newDeployedsDSWrapper(d, meta)
	lisDepResRst, err := wrapper.ListDeployedResources()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listDeployedResourcesToSchema(lisDepResRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API SCM POST /v3/scm/deployed-resources
func (w *DeployedsDSWrapper) ListDeployedResources() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "scm")
	if err != nil {
		return nil, err
	}

	uri := "/v3/scm/deployed-resources"
	params := map[string]any{
		"certificate_ids": w.ListToArray("certificate_ids"),
		"service_names":   w.ListToArray("service_names"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("POST").
		URI(uri).
		Body(params).
		Request().
		Result()
}

func (w *DeployedsDSWrapper) listDeployedResourcesToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("results", schemas.SliceToList(body.Get("results"),
			func(results gjson.Result) any {
				return map[string]any{
					"certificate_id": results.Get("certificate_id").Value(),
					"total_num":      results.Get("total_num").Value(),
					"deployed_resources": schemas.SliceToList(results.Get("deployed_resources"),
						func(deployedResources gjson.Result) any {
							return map[string]any{
								"region_resources":  w.setResDepResRegRes(deployedResources),
								"service":           deployedResources.Get("service").Value(),
								"resource_num":      deployedResources.Get("resource_num").Value(),
								"resource_location": deployedResources.Get("resource_location").Value(),
							}
						},
					),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}

func (*DeployedsDSWrapper) setResDepResRegRes(deployedResources gjson.Result) any {
	return schemas.SliceToList(deployedResources.Get("region_resources"), func(regionResources gjson.Result) any {
		return map[string]any{
			"region_id": regionResources.Get("region_id").Value(),
			"is_error":  regionResources.Get("is_error").Value(),
			"resources": schemas.SliceToList(regionResources.Get("resources"),
				func(resources gjson.Result) any {
					return map[string]any{
						"resource_id":   resources.Get("resource_id").Value(),
						"resource_name": resources.Get("resource_name").Value(),
					}
				},
			),
		}
	})
}
