// Generated by PMS #964
package ecs

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
)

func DataSourceEcsComputePassword() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceEcsComputePasswordRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"server_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ECS ID.`,
			},
			"password": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: `Indicates the password in ciphertext.`,
			},
		},
	}
}

type ComputePasswordDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newComputePasswordDSWrapper(d *schema.ResourceData, meta interface{}) *ComputePasswordDSWrapper {
	return &ComputePasswordDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceEcsComputePasswordRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newComputePasswordDSWrapper(d, meta)
	shoSerPasRst, err := wrapper.ShowServerPassword()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.showServerPasswordToSchema(shoSerPasRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API ECS GET /v1/{project_id}/cloudservers/{server_id}/os-server-password
func (w *ComputePasswordDSWrapper) ShowServerPassword() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "ecs")
	if err != nil {
		return nil, err
	}

	uri := "/v1/{project_id}/cloudservers/{server_id}/os-server-password"
	uri = strings.ReplaceAll(uri, "{server_id}", w.Get("server_id").(string))
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Request().
		Result()
}

func (w *ComputePasswordDSWrapper) showServerPasswordToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("password", body.Get("password").Value()),
	)
	return mErr.ErrorOrNil()
}
