vpc_name                = "tf_test_vpc"
subnet_name             = "tf_test_subnet"
security_group_name     = "tf_test_security_group"
instance_name           = "tf_test_geminidb_redis_instance"
parameter_template_name = "tf_test_redis_parameter_template"
