// Generated by PMS #539
package gaussdb

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
)

func DataSourceGaussdbOpengaussInstanceFeatures() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceGaussdbOpengaussInstanceFeaturesRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of the GaussDB OpenGauss instance.`,
			},
			"features": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `Indicates the advanced features.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature name.`,
						},
						"status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates whether the feature is enabled.`,
						},
						"description": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature description.`,
						},
						"type": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature value type.`,
						},
						"value": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature value.`,
						},
						"range": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature value range.`,
						},
						"range_description": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `Indicates the feature scope description.`,
						},
					},
				},
			},
		},
	}
}

type OpengaussInstanceFeaturesDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newOpengaussInstanceFeaturesDSWrapper(d *schema.ResourceData, meta interface{}) *OpengaussInstanceFeaturesDSWrapper {
	return &OpengaussInstanceFeaturesDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceGaussdbOpengaussInstanceFeaturesRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newOpengaussInstanceFeaturesDSWrapper(d, meta)
	listFeaturesRst, err := wrapper.ListFeatures()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.listFeaturesToSchema(listFeaturesRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API GaussDB GET /v3/{project_id}/instances/{instance_id}/advance-features
func (w *OpengaussInstanceFeaturesDSWrapper) ListFeatures() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "opengauss")
	if err != nil {
		return nil, err
	}

	uri := "/v3/{project_id}/instances/{instance_id}/advance-features"
	uri = strings.ReplaceAll(uri, "{instance_id}", w.Get("instance_id").(string))
	return httphelper.New(client).
		Method("GET").
		URI(uri).
		Request().
		Result()
}

func (w *OpengaussInstanceFeaturesDSWrapper) listFeaturesToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("features", schemas.SliceToList(body.Get("features"),
			func(features gjson.Result) any {
				return map[string]any{
					"name":              features.Get("name").Value(),
					"status":            features.Get("status").Value(),
					"description":       features.Get("description").Value(),
					"type":              features.Get("type").Value(),
					"value":             features.Get("value").Value(),
					"range":             features.Get("range").Value(),
					"range_description": features.Get("range_description").Value(),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
