info:
    version: ""
    title: data_source_huaweicloud_ddm_configuration_parameters
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: DDM
paths:
    /v3/{project_id}/configurations/{config_id}:
        GET:
            tag: DDM
