info:
    version: ""
    title: data_source_huaweicloud_dws_om_account_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: DWS
paths:
    /v1/{project_id}/clusters/{cluster_id}/db-manager/om-user/status:
        GET:
            tag: DWS
