info:
    version: ""
    title: data_source_huaweicloud_cse_microservice_engine_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CSE
paths:
    /v1/{project_id}/kie/kv:
        GET:
            tag: CSE
