info:
    version: ""
    title: data_source_huaweicloud_workspace_app_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/bundles/batch-query-config-info:
        POST:
            tag: Workspace
