info:
    version: ""
    title: data_source_huaweicloud_coc_application_capacity_orders
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/capacity/order:
        GET:
            tag: COC
