info:
    version: ""
    title: data_source_huaweicloud_hss_container_kubernetes_clusters_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: HSS
paths:
    /v5/{project_id}/container/kubernetes/clusters/configs/batch-query:
        POST:
            tag: HSS
