info:
    version: ""
    title: data_source_huaweicloud_coc_application_views
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/application-view/search:
        GET:
            tag: COC
