info:
    version: ""
    title: data_source_huaweicloud_antiddos_config_ranges
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ANTI-DDOS
paths:
    /v2/{project_id}/antiddos/query-config-list:
        GET:
            tag: ANTI-DDOS
