info:
    version: ""
    title: data_source_huaweicloud_rds_lts_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RDS
paths:
    /v3/{project_id}/{engine}/instances/logs/lts-configs:
        GET:
            tag: RDS
