info:
    version: ""
    title: data_source_huaweicloud_coc_application_capacities
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/capacity:
        POST:
            tag: COC
