info:
    version: ""
    title: data_source_huaweicloud_secmaster_collect_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: SecMaster
paths:
    /v1/{project_id}/collector/cloudlogs/config:
        GET:
            tag: SecMaster
