info:
    version: ""
    title: data_source_huaweicloud_apig_application_associated_quota
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: APIG
paths:
    /v2/{project_id}/apigw/instances/{instance_id}/apps/{app_id}/bound-quota:
        GET:
            tag: APIG
