info:
    version: ""
    title: data_source_huaweicloud_workspace_app_hda_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/app-servers/access-agent/list:
        GET:
            tag: Workspace
