info:
    version: ""
    title: data_source_huaweicloud_identitycenter_service_provider_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/identity-stores/{identity_store_id}/sp-config:
        GET:
            tag: IdentityCenter
