info:
    version: ""
    title: data_source_huaweicloud_rds_instance_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RDS
paths:
    /v3/{project_id}/instances/{instance_id}/configurations:
        GET:
            tag: RDS
