info:
    version: ""
    title: data_source_huaweicloud_fgs_async_invoke_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: FunctionGraph
paths:
    /v2/{project_id}/fgs/functions/{function_urn}/async-invoke-configs:
        GET:
            tag: FunctionGraph
