info:
    version: ""
    title: data_source_huaweicloud_codearts_deploy_environments
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v1/applications/{application_id}/environments:
        GET:
            tag: CodeArtsDeploy
