info:
    version: ""
    title: data_source_huaweicloud_elb_loadbalancer_feature_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ELB
paths:
    /v3/{project_id}/elb/loadbalancers/{loadbalancer_id}/features:
        GET:
            tag: ELB
