info:
    version: ""
    title: data_source_huaweicloud_secmaster_configuration_dictionaries
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: SecMaster
paths:
    /v1/{project_id}/configurations/dictionaries:
        GET:
            tag: SecMaster
