info:
    version: ""
    title: data_source_huaweicloud_servicestagev3_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ServiceStage
paths:
    /v3/{project_id}/cas/applications:
        GET:
            tag: ServiceStage
