info:
    version: ""
    title: data_source_huaweicloud_ddm_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: DDM
paths:
    /v3/{project_id}/configurations:
        GET:
            tag: DDM
