info:
    version: ""
    title: data_source_huaweicloud_identitycenter_catalog_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: IdentityCenter
paths:
    /v1/catalog/applications:
        GET:
            tag: IdentityCenter
