info:
    version: ""
    title: data_source_huaweicloud_elb_feature_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ELB
paths:
    /v3/{project_id}/elb/feature/configs:
        GET:
            tag: ELB
