info:
    version: ""
    title: data_source_huaweicloud_gaussdb_instance_lts_log_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: GaussDB
paths:
    /v3/{project_id}/instances/logs/lts-config:
        GET:
            tag: GaussDB
