info:
    version: ""
    title: data_source_huaweicloud_codearts_deploy_application_groups
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v1/projects/{project_id}/applications/groups:
        GET:
            tag: CodeArtsDeploy
