info:
    version: ""
    title: data_source_huaweicloud_sms_agent_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: SMS
paths:
    /v3/config:
        GET:
            tag: SMS
