info:
    version: ""
    title: data_source_huaweicloud_dds_pt_application_records
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: DDS
paths:
    /v3/{project_id}/configurations/{config_id}/applied-histories:
        GET:
            tag: DDS
