info:
    version: ""
    title: data_source_huaweicloud_coc_application_next_models
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/application-model/next:
        GET:
            tag: COC
