info:
    version: ""
    title: data_source_huaweicloud_workspace_app_latest_attached_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/image-servers/{server_id}/actions/latest-attached-app:
        GET:
            tag: Workspace
