info:
    version: ""
    title: data_source_huaweicloud_waf_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: WAF
paths:
    /v1/{project_id}/waf/config/console:
        GET:
            tag: WAF
