info:
    version: ""
    title: data_source_huaweicloud_cc_global_connection_bandwidth_configs
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CC
paths:
    /v3/{domain_id}/gcb/configs:
        GET:
            tag: CC
