info:
    version: ""
    title: data_source_huaweicloud_gaussdb_mysql_configurations
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: GaussDBforMySQL
paths:
    /v3/{project_id}/configurations:
        GET:
            tag: GaussDBforMySQL
