info:
    version: ""
    title: data_source_huaweicloud_coc_applications
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/applications:
        GET:
            tag: COC
