info:
    version: ""
    title: resource_huaweicloud_workspace_app_application_batch_attach
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: Workspace
paths:
    /v1/{project_id}/image-servers/{server_id}/actions/attach-app:
        POST:
            tag: Workspace
