info:
    version: ""
    title: resource_huaweicloud_gaussdb_mysql_instance_node_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: GaussDBforMySQL
paths:
    /v3/{project_id}/instances/{instance_id}:
        GET:
            tag: GaussDBforMySQL
    /v3/{project_id}/instances/{instance_id}/nodes/{node_id}/priority:
        PUT:
            tag: GaussDBforMySQL
    /v3/{project_id}/instances/{instance_id}/nodes/name:
        PUT:
            tag: GaussDBforMySQL
    /v3/{project_id}/instances/details:
        GET:
            tag: GaussDBforMySQL
    /v3/{project_id}/jobs:
        GET:
            tag: GaussDBforMySQL
