info:
    version: ""
    title: resource_huaweicloud_servicestagev3_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ServiceStage
paths:
    /v3/{project_id}/cas/applications:
        POST:
            tag: ServiceStage
    /v3/{project_id}/cas/applications/{application_id}:
        DELETE:
            tag: ServiceStage
        GET:
            tag: ServiceStage
        PUT:
            tag: ServiceStage
