info:
    version: ""
    title: resource_huaweicloud_cce_cluster_log_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CCE
paths:
    /api/v3/projects/{project_id}/cluster/{cluster_id}/log-configs:
        GET:
            tag: CCE
        PUT:
            tag: CCE
