info:
    version: ""
    title: resource_huaweicloud_servicestagev3_configuration
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ServiceStage
paths:
    /v3/{project_id}/cas/configs:
        POST:
            tag: ServiceStage
    /v3/{project_id}/cas/configs/{config_id}:
        DELETE:
            tag: ServiceStage
        GET:
            tag: ServiceStage
        PUT:
            tag: ServiceStage
