info:
    version: ""
    title: resource_huaweicloud_codearts_deploy_application_group
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v1/projects/{project_id}/applications/groups:
        GET:
            tag: CodeArtsDeploy
        POST:
            tag: CodeArtsDeploy
    /v1/projects/{project_id}/applications/groups/{group_id}:
        DELETE:
            tag: CodeArtsDeploy
        PUT:
            tag: CodeArtsDeploy
