info:
    version: ""
    title: resource_huaweicloud_codearts_deploy_environment_permission
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v2/applications/{application_id}/environments/{environment_id}/permissions:
        GET:
            tag: CodeArtsDeploy
        PUT:
            tag: CodeArtsDeploy
