info:
    version: ""
    title: resource_huaweicloud_drs_job_configuration_update
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: DRS
paths:
    /v5/{project_id}/jobs/{job_id}/modify-configuration:
        PUT:
            tag: DRS
