info:
    version: ""
    title: resource_huaweicloud_codearts_deploy_application_copy
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: CodeArtsDeploy
paths:
    /v1/applications:
        PUT:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}:
        DELETE:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}/disable:
        PUT:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}/duplicate:
        POST:
            tag: CodeArtsDeploy
    /v1/applications/{app_id}/info:
        GET:
            tag: CodeArtsDeploy
    /v1/projects/{project_id}/applications/groups/move:
        PUT:
            tag: CodeArtsDeploy
    /v3/applications/permission-level:
        PUT:
            tag: CodeArtsDeploy
    /v3/applications/permissions:
        GET:
            tag: CodeArtsDeploy
