info:
    version: ""
    title: resource_huaweicloud_coc_application
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: COC
paths:
    /v1/applications:
        GET:
            tag: COC
        POST:
            tag: COC
    /v1/applications/{id}:
        DELETE:
            tag: COC
        PUT:
            tag: COC
