info:
    version: ""
    title: resource_huaweicloud_secmaster_collect_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: SecMaster
paths:
    /v1/{project_id}/collector/cloudlogs/config:
        POST:
            tag: SecMaster
