info:
    version: ""
    title: resource_huaweicloud_servicestagev3_environment
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: ServiceStage
paths:
    /v3/{project_id}/cas/environments:
        POST:
            tag: ServiceStage
    /v3/{project_id}/cas/environments/{environment_id}:
        DELETE:
            tag: ServiceStage
        GET:
            tag: ServiceStage
        PUT:
            tag: ServiceStage
