info:
    version: ""
    title: resource_huaweicloud_rds_lts_config
    description: ""
schemes:
    - https
host: huaweicloud.com
tags:
    - name: RDS
paths:
    /v3/{project_id}/{engine}/instances/logs/lts-configs:
        DELETE:
            tag: RDS
        GET:
            tag: RDS
        POST:
            tag: RDS
