vpc_name              = "tf_test_apig_instance_vpc"
subnet_name           = "tf_test_apig_instance_subnet"
security_group_name   = "tf_test_apig_instance_security_group"
instance_name         = "tf_test_apig_instance"
enterprise_project_id = "0"
plugin_name           = "tf_test_apig_plugin"
plugin_description    = "Created by Terraform script"
